default:
  path: ".."
  pattern: "^(LC).*all mosquitoes.(xlsx|csv)$" #pattern to look for in fun_read_list 
  fn_trap_keep: "../1_input/foco_trap.csv"
  fn_database: "../1_input/wnv-s_database.csv"
  fn_rename_col: "../1_input/database_column_rename.csv" #column used to rename the input data to the wnv-s_database format
  na_col: "trap_id" #na_col for culex_filter
  filter_active: "TRUE" #whether you want to only keep the active traps for
  output_culex_database: "../3_output/culex_sheet_database_augment.csv"
  output_trap_all: "../3_output/trap_database_all_spp.csv"
  output_plot_abund: "../3_output/culex_sheet_combined_abundance.png"
  output_plot_comp: "../3_output/culex_v_datasheet.png"
  output_plot_n_trap: "../3_output/n_trap_per_wk_culex_sheet.png"
  filter_zone:
    - "BC"
    - "BE"
  fc_zone:
    - "NE"
    - "NW"
    - "SE"
    - "SW"

culex:
  pattern: "^(LC|Boulder).*Culex.(xlsx|csv)$" #pattern to look for in fun_read_list 